parse_config:
  mark_alternate_layer_activators: true
  modifier_fn_map:
    left_ctrl: ^
    right_ctrl: ^
    left_shift: ⇧
    right_shift: ⇧
    left_alt: ⌥
    right_alt: ⌥
    left_gui: ⌘
    right_gui: ⌘
    keycode_combiner: '{mods}{key}'
    mod_combiner: '{mod_1}{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_keycode_map:
    # overrides
    LEFT_SHIFT: ⇧
    LSHIFT: ⇧
    BACKSPACE: ⌫
    BSPC: ⌫
    SPACE: ␣
    DELETE: ⌦
    LEFT_ALT: ⌥
    LALT: ⌥
    LEFT_COMMAND: ⌘
    LEFT_CONTROL: ^
    LCTRL: ^
    UP_ARROW: ↑
    DOWN_ARROW: ↓
    LEFT_ARROW: ←
    RIGHT_ARROW: →
    ENTER: ↵
    TAB: ⇥
    LS(TAB): ⇤
    LS(LC(TAB)): ^⇤
    # defaults
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: "$"
    DLLR: "$"
    PERCENT: "%"
    PRCNT: "%"
    CARET: "^"
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: "("
    LPAR: "("
    RIGHT_PARENTHESIS: ")"
    RPAR: ")"
    EQUAL: "="
    PLUS: "+"
    MINUS: "-"
    UNDERSCORE: "_"
    UNDER: "_"
    SLASH: "/"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: "\\"
    BSLH: "\\"
    PIPE: "|"
    NON_US_BACKSLASH: "\\"
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ";"
    SEMI: ";"
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: "<"
    LT: "<"
    PERIOD: "."
    DOT: "."
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

draw_config:
  separate_combo_diagrams: true
  combo_diagrams_scale: 4
  svg_extra_style: |
    rect.held.alternate { fill: #bee9e9; }
    @media (prefers-color-scheme: dark) { rect.held.alternate { fill: #6a9b9b; } }
    svg.keymap { font-family: "Noto Sans Symbols2","Segoe UI Symbol",SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace; }
  dark_mode: auto
